steps:
  # Install dependencies and build Node.js application
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','us-central1.docker.pkg.dev/gcpproject-410115/noderepository/noderepository:v1','.']
images:
- "us-central1.docker.pkg.dev/gcpproject-410115/noderepository/noderepository:v1"