steps:
  # Install dependencies and build Node.js application
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','us-east1.docker.pkg.dev/gcpproject-410115/myrepo/myrepo:v1','.']
images:
- "us-east1.docker.pkg.dev/gcpproject-410115/myrepo/myrepo:v1"