steps:
  # Install dependencies and build Node.js application
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','us-central1.docker.pkg.dev/$PROJECT_ID/noderepository/node:v1','.']
images:
- "us-central1.docker.pkg.dev/$PROJECT_ID/noderepository/node:v1"